name: Deploy
on: 
  push:
    branches: [ dev]

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
    
    - name: lint
      run: npm run lint
    
    - name: Unit tests
      run: npm run test
    
  build: 
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
      
    - name: Build app
      run: npm run watch 
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with: 
        name: brief-vps-${{ github.run_id }}-${{ github.run_number }}
        path: ./dist/brief-vps

  deploy: 
    needs: build
    runs-on: ubuntu-latest

    steps: 
    - name: Dowload artifact
      uses: actions/download-artifact@v2
      with: 
        name: brief-vps-${{ github.run_id }}-${{ github.run_number }} 
        path: './brief-vps'

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "./brief-vps/"
        target: "/var/www/"